/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as NewPostIndexImport } from './routes/new-post/index'
import { Route as PostsListTypeImport } from './routes/posts/list.$type'
import { Route as PostsDetailPostIdImport } from './routes/posts/detail.$postId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const NewPostIndexRoute = NewPostIndexImport.update({
  id: '/new-post/',
  path: '/new-post/',
  getParentRoute: () => rootRoute,
} as any)

const PostsListTypeRoute = PostsListTypeImport.update({
  id: '/posts/list/$type',
  path: '/posts/list/$type',
  getParentRoute: () => rootRoute,
} as any)

const PostsDetailPostIdRoute = PostsDetailPostIdImport.update({
  id: '/posts/detail/$postId',
  path: '/posts/detail/$postId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/new-post/': {
      id: '/new-post/'
      path: '/new-post'
      fullPath: '/new-post'
      preLoaderRoute: typeof NewPostIndexImport
      parentRoute: typeof rootRoute
    }
    '/posts/detail/$postId': {
      id: '/posts/detail/$postId'
      path: '/posts/detail/$postId'
      fullPath: '/posts/detail/$postId'
      preLoaderRoute: typeof PostsDetailPostIdImport
      parentRoute: typeof rootRoute
    }
    '/posts/list/$type': {
      id: '/posts/list/$type'
      path: '/posts/list/$type'
      fullPath: '/posts/list/$type'
      preLoaderRoute: typeof PostsListTypeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new-post': typeof NewPostIndexRoute
  '/posts/detail/$postId': typeof PostsDetailPostIdRoute
  '/posts/list/$type': typeof PostsListTypeRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new-post': typeof NewPostIndexRoute
  '/posts/detail/$postId': typeof PostsDetailPostIdRoute
  '/posts/list/$type': typeof PostsListTypeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/new-post/': typeof NewPostIndexRoute
  '/posts/detail/$postId': typeof PostsDetailPostIdRoute
  '/posts/list/$type': typeof PostsListTypeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/new-post' | '/posts/detail/$postId' | '/posts/list/$type'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/new-post' | '/posts/detail/$postId' | '/posts/list/$type'
  id:
    | '__root__'
    | '/'
    | '/new-post/'
    | '/posts/detail/$postId'
    | '/posts/list/$type'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewPostIndexRoute: typeof NewPostIndexRoute
  PostsDetailPostIdRoute: typeof PostsDetailPostIdRoute
  PostsListTypeRoute: typeof PostsListTypeRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewPostIndexRoute: NewPostIndexRoute,
  PostsDetailPostIdRoute: PostsDetailPostIdRoute,
  PostsListTypeRoute: PostsListTypeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/new-post/",
        "/posts/detail/$postId",
        "/posts/list/$type"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/new-post/": {
      "filePath": "new-post/index.tsx"
    },
    "/posts/detail/$postId": {
      "filePath": "posts/detail.$postId.tsx"
    },
    "/posts/list/$type": {
      "filePath": "posts/list.$type.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
