name: Build check before PR

on:
  pull_request:
    branches: ['main', 'release']
jobs:
  build:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build project
        run: pnpm build
